[[imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[[imports]]
path = "github.com/emanueles/dc-idc-2025.1"
[[imports.mounts]]
source = "."
target = "content/post/2025.1"

[[imports]]
path = "github.com/emanueles/dc-idc-2026.1"
[[imports.mounts]]
source = "."
target = "content/post/2026.1"